language: haxe

os:
  - linux
  - osx

haxe:
  - "3.2.1"
  - development

sudo: false

install:
  - haxelib dev hxcs .
  - haxelib list

script:
  - pushd build-tool
  -   haxe build-cs.hxml
  - popd
